#!/bin/bash

SUFFIX="dc=`echo $LDAP_DOMAIN | sed 's/^\.//; s/\.$//; s/\./,dc=/g'`"
CN_ADMIN="cn=admin,ou=aclroles,$SUFFIX"
UID_FD_ADMIN="uid=fd-admin,ou=people,$SUFFIX"
CN_ADMIN_BS64=`php-cli -r "echo base64_encode('$CN_ADMIN');"`
UID_FD_ADMIN_BS64=`php-cli -r "echo base64_encode('$UID_FD_ADMIN');"`

cat <<EOF > "/tmp/ldap-base"
dn: @SUFFIX@
objectClass: top
objectClass: dcObject
objectClass: organization
objectClass: gosaDepartment
objectClass: gosaAcl
gosaAclEntry: 0:subtree:$CN_ADMIN_BS64:$UID_FD_ADMIN_BS64
o: @ORGANIZATION@
dc: @DOMAINCOMPONENT@
ou: @DOMAINCOMPONENT@
description: @DOMAINCOMPONENT@ in @ORGANIZATION@

dn: cn=admin,@SUFFIX@
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: admin
description: LDAP administrator
userPassword: @PASSWORD@
EOF

. start-slapd
