#!/bin/bash

cat <<EOF > "/tmp/ldap-base"
dn: @SUFFIX@
objectClass: top
objectClass: dcObject
objectClass: organization
objectClass: gosaDepartment
objectClass: gosaAcl
gosaAclEntry: 0:subtree:Y249YWRtaW4sb3U9YWNscm9sZXMsZGM9ZXhhbXBsZSxkYz1jb20=:d
 WlkPWZkLWFkbWluLG91PXBlb3BsZSxkYz1leGFtcGxlLGRjPWNvbQ==
o: @ORGANIZATION@
dc: @DOMAINCOMPONENT@
ou: @DOMAINCOMPONENT@
description: @DOMAINCOMPONENT@ in @ORGANIZATION@

dn: cn=admin,@SUFFIX@
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: admin
description: LDAP administrator
userPassword: @PASSWORD@
EOF

. start-slapd